[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.9.8"
x86 = "0.52.0"
uart_16550 = "0.6.0"

[profile.dev]

[profile.test]
opt-level = 1
debug = false 
[profile.release]

lto = true
codegen-units = 1
strip = "symbols"
opt-level = 1

[[bin]]
name = "kernel"
test = true
bench = false